- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Python & dependencies
  raw: sudo apt -y install {{item}}
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip
    - python-mysqldb