- name: Install Python & dependencies
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-setuptools
    - python-environment
    - build-essential
    - python-pip
    - python-mysqldb